// Code generated by "stringer -type=gcTag -output=certs_string.go"; DO NOT EDIT

package main

import "fmt"

const _gcTag_name = "tagSignatureAlgorithmstagSupportedGroupstagECDSACipher"

var _gcTag_index = [...]uint8{0, 22, 40, 54}

func (i gcTag) String() string {
	i -= 1
	if i >= gcTag(len(_gcTag_index)-1) {
		return fmt.Sprintf("gcTag(%d)", i+1)
	}
	return _gcTag_name[_gcTag_index[i]:_gcTag_index[i+1]]
}
