// Code generated by "stringer -type=Op -output=opcodes_string.go"; DO NOT EDIT

package keyless

import "fmt"

const (
	_Op_name_0 = "OpRSADecryptOpRSASignMD5SHA1OpRSASignSHA1OpRSASignSHA224OpRSASignSHA256OpRSASignSHA384OpRSASignSHA512OpRSADecryptRaw"
	_Op_name_1 = "OpECDSASignMD5SHA1OpECDSASignSHA1OpECDSASignSHA224OpECDSASignSHA256OpECDSASignSHA384OpECDSASignSHA512"
	_Op_name_2 = "OpGetCertificate"
	_Op_name_3 = "OpRSAPSSSignSHA256OpRSAPSSSignSHA384OpRSAPSSSignSHA512"
	_Op_name_4 = "OpResponseOpPingOpPongOpActivate"
	_Op_name_5 = "OpError"
	_Op_name_6 = "OpEd25519Sign"
)

var (
	_Op_index_0 = [...]uint8{0, 12, 28, 41, 56, 71, 86, 101, 116}
	_Op_index_1 = [...]uint8{0, 18, 33, 50, 67, 84, 101}
	_Op_index_2 = [...]uint8{0, 16}
	_Op_index_3 = [...]uint8{0, 18, 36, 54}
	_Op_index_4 = [...]uint8{0, 10, 16, 22, 32}
	_Op_index_5 = [...]uint8{0, 7}
	_Op_index_6 = [...]uint8{0, 13}
)

func (i Op) String() string {
	switch {
	case 1 <= i && i <= 8:
		i -= 1
		return _Op_name_0[_Op_index_0[i]:_Op_index_0[i+1]]
	case 18 <= i && i <= 23:
		i -= 18
		return _Op_name_1[_Op_index_1[i]:_Op_index_1[i+1]]
	case i == 32:
		return _Op_name_2
	case 53 <= i && i <= 55:
		i -= 53
		return _Op_name_3[_Op_index_3[i]:_Op_index_3[i+1]]
	case 240 <= i && i <= 243:
		i -= 240
		return _Op_name_4[_Op_index_4[i]:_Op_index_4[i+1]]
	case i == 255:
		return _Op_name_5
	case i == 257:
		return _Op_name_6
	default:
		return fmt.Sprintf("Op(%d)", i)
	}
}
